#!/bin/bash

# when errors quit
set -e

echo "Starting with updating the system"
# make function to run system updates

update() {
echo "Checking for updates"
sudo apt-get update
echo "Installing updates if available"
sudo apt-get upgrade -yy
}

node() {
echo "Updating node to latest LTS version"
nvm install --lts
}


clean() {
echo "Cleaning up files that are no longer needed"
sudo apt-get autoremove -yy
sudo apt-get autoclean
}


#run those functions

update
clean

# read -p "Want to install node LTS? (y/n)" answer
# case ${answer:0:1} in
#     y|Y )
#         node
#     ;;
#     * )
#         break
#     ;;
# esac

echo "Exiting the script"

exit
